version: '3'

services:
  redis:
    image: redis:alpine
    env_file: ./.env
    networks:
      - backend
    volumes:
      - ./redis_data:/data
  app:
    build:
      context: .
    env_file: ./.env
    depends_on:
      - redis
    links:
      - redis
    networks:
      - backend
    volumes:
      - ./app:/home/node/app/app
  server:
    build: ./server
    env_file: ./.env
    ports:
      - 8000:8000
    depends_on:
      - redis
    links:
      - redis
    networks:
      - backend
    volumes:
      - ./server/app:/home/node/server/app

networks:
  backend: