version: '3'

services:
  redis:
    image: redis:alpine
    env_file: ./.env
    ports:
      - 6379:6379
    networks:
      - backend
  app:
    build:
      context: .
    depends_on:
      - redis
    links:
      - redis
    networks:
      - backend
    volumes:
      - .:/home/node/app
  server:
    build: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server:/home/node/app

networks:
  backend: